version: "3.9"

networks:
  studycleanarchitecture-net:
    driver: bridge

services:
  pessoa-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "pessoa"
    ports:
      - "5432:5432"
    networks:
      - studycleanarchitecture-net

  config-server:
    image: rospiel/config-server
    environment:
      GITHUB_USER: "${GITHUB_USER}"
      GITHUB_PASS: "${GITHUB_PASS}"
    ports:
      - "8888:8888"
    networks:
      - studycleanarchitecture-net         