version: "3.9"

networks:
  studycleanarchitecture-net:
    driver: bridge

services:
  pessoa-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "pessoa"
    ports:
      - "5432:5432"
    networks:
      - studycleanarchitecture-net

  config-server:
    image: rospiel/config-server
    environment:
      GITHUB_USER: "${GITHUB_USER}"
      GITHUB_PASS: "${GITHUB_PASS}"
    ports:
      - "8888:8888"
    networks:
      - studycleanarchitecture-net

  eureka-server:
    image: rospiel/eureka-server
    ports:
      - "8761:8761"
    networks:
      - studycleanarchitecture-net

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8080:8080"
    networks:
      - studycleanarchitecture-net    

  ms-pessoa:
    image: rospiel/ms-pessoa
    command: ["/wait-for-it.sh", "-t", "30", "keycloak:8080",
              "--", "java", "-jar", "api.jar"]
    environment: 
      TOKEN_CHAVE_PUBLICA: "${TOKEN_CHAVE_PUBLICA}"
      TOKEN_MODELO_ALGORITMO: "${TOKEN_MODELO_ALGORITMO}"
    ports:
      - "8080"
    networks:
      - studycleanarchitecture-net
    depends_on:
      - pessoa-db
      - config-server  
      - eureka-server

